# Generated by Django 4.2.30 on 2026-05-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
