# Generated by Django 4.2.30 on 2026-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0002_activityrecord_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='co2_emission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='emission_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='source_type',
            field=models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('failed', 'Failed'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
