# Generated by Django 4.2.30 on 2026-05-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
