# Generated by Django 4.2.30 on 2026-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0005_activityrecord_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='co2_emission',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
